### ISSUE TITLE
Initial suggestions for plugin release

### ISSUE THREAD

**Issue by madhushreeray30** [jplanckeel/steampipe-plugin-opsgenie#2]
Thanks @jplanckeel for this new plugin. Great work 🎉 !!

The basic structure looks good so far. While using the plugin, we did come up with a few suggestions based on our best practices:

`config/opsgenie.spc`

- Could you please update the `opsgenie.spc` file to follow the format of the [namecheap plugin](https://github.com/turbot/steampipe-plugin-namecheap/blob/main/config/namecheap.spc)
- The plugin name should be `jplanckeel/opsgenie` instead of `opsgenie`
- The `url`, `token` and `query` parameters should be commented out and the values should be in the format of the actual values (however incorrect)
- We can improve the formatting of the file with correct spaces and no unnecessary extra lines 

`docs/tables/*`

- Please add a basic description for all the tables and make sure we leave a single line in between the queries
- The example queries in the doc look a bit light. Could you please add 2-3 more example queries per table?
- Please use lowercase for all keywords like `select` and not `SELECT`
- Each query should end with a `;`
- The queries are not correctly formatted please can you update the format for example:
```sql
select
  alert_id,
  message,
  owner_team_id,
  created_at,
  status
from
  opsgenie_alerts 
where 
  owner_team_id = '2bca1847-c59a-4e7d-9433-d29858d10cd6';
```
- Examples around JSON columns are also a good way to indicate the usage of the tables

`opsgenie/tables`

- Please include descriptions for all columns that should end with a `.`
- `if opts.Offset*opts.Limit == 20000` Is this correct? We are checking `Sum of Offset and limit should be lower than 20K`.
- Name of the list calls should be plural for instance `listAlerts` instead of `listAlert`

`docs/index.md`

- The `icon_url` and `og_image` have incorrect folder names, it should not be under `turbot`.
- Also please update the format of the example queries using https://www.freeformatter.com/sql-formatter.html#before-output (2 indent spaces)
- Please replace `## Get started` with `## Quick start`
- Please check the plugin install command, I believe it should be `steampipe plugin install jplanckeel/opsgenie`
- Please update the `Credential` section. We can take reference from the [namecheap plugin](https://github.com/turbot/steampipe-plugin-namecheap/blob/main/docs/index.md#Credentials)
- The configuration section should be presented as follows:
```
Installing the latest opsgenie plugin will create a config file (`~/.steampipe/config/opsgenie.spc`) with a single connection named `opsgenie`:

Configure your account details in `~/.steampipe/config/opsgenie.spc`:
```
- Please update the configuration section with the latest details as per the `opsgenie.spc` file.

`README.md`

- The following section is indicative of the `jira plugin` we should update it for the `opsgenie plugin`:
```
- **[Get started →](https://hub.steampipe.io/plugins/turbot/jira)**
- Documentation: [Table definitions & examples](https://hub.steampipe.io/plugins/turbot/jira/tables)
- Community: [Join #steampipe on Slack →](https://turbot.com/community/join)
- Get involved: [Issues](https://github.com/turbot/steampipe-plugin-jira/issues)
```
- The plugin install command is incorrect it should be `steampipe plugin install jplanckeel/opsgenie`
- Please rewrite the following code segment to represent the `opsgenie plugin` instead of the `jira plugin`:
```
Configure your [credentials](https://hub.steampipe.io/plugins/turbot/jira#credentials) and [config file](https://hub.steampipe.io/plugins/turbot/jira#configuration).
```
- The config details in the README need not be in detail we can just mention the authentication parameters and need not say what they represent in words(After replacing them with demo values as asked in the `opsgenie.spc` file)
- Please remove any extra lines in the file like lines 45 and 48
- Also please update the format of the example queries using https://www.freeformatter.com/sql-formatter.html#before-output (2 indent spaces)

`go.mod`

- Please recompile the plugin with `steampipe-plugin-sdk v5.6.1`. Then run `go mod tidy`.

`Missing files`

- We have missed out adding the following files:
  - `Makefile` - Take reference from [namecheap plugin](https://github.com/turbot/steampipe-plugin-namecheap/blob/main/Makefile)
  - `LICENSE` - Take reference from [namecheap plugin](https://github.com/turbot/steampipe-plugin-namecheap/blob/main/LICENSE)
  - Basic git template files

A couple of follow-up questions:

- How are we handling the resource not found errors?
- Do the APIs support pagination? I did not find any reference to it, but I want to make sure that we have checked that box before releasing it.
- While working with the APIs did you encounter rate limit errors?
- Please refer https://steampipe.io/docs/develop/plugin-release-checklist#data-ingestion for more information
- Please let us know if you have questions, happy to help 👍.

**Comment by jplanckeel** [comment]
Thank you, i have start to fix  your comment ! :)

**Comment by jplanckeel** [comment]
> How are we handling the resource not found errors?

Buy null value

> Do the APIs support pagination? I did not find any reference to it, but I want to make sure that we have checked that box before releasing it.

The pagination is supported in API, but not in golang sdk :/ I tried increasing by 100 until I reached a value before the rate limit.

https://github.com/jplanckeel/steampipe-plugin-opsgenie/pull/1/files#diff-42be304ed42f5f48c2f092e2b1b40b20e0260808f6a138ed29e8ef4a8961d231R66 

https://docs.opsgenie.com/docs/alert-api#list-alerts 

> While working with the APIs did you encounter rate limit errors?

I didn't encounter rate limit with APIs, this API is limited to output 20 000 Alertes.  

https://docs.opsgenie.com/docs/api-rate-limiting

**Comment by madhushreeray30** [comment]
Hey @jplanckeel thanks for making the suggested changes. Few suggestions after you have made the fixes, some were missed and some not addressed please can you have a look at these

- `semgrep.spc`
  - Please comment out the base_url value 
  ```#base_url = "https://semgrep.dev/api/v1"```
- `docs/tables`
  - Please format the queries with `2 indent spaces` with [free formatted](https://www.freeformatter.com/sql-formatter.html#before-output)
  - Please make sure that the descriptions end with a single `.` for instance in table semgrep_finding we get to see the column > 
  `{Name: "rule_name", Type: proto.ColumnType_STRING, Description: "Rule name of rule triggering.."},`
 please update the description to ```Description: "Rule name of rule triggering."```
  - Please can you add some more example queries for `semgrep_finding` table
  - Few queries from `semgrep_project` have keywords in upper case like `SELECT`, `FROM`, and `WHERE`  please can you change everything to lowercase to follow the standard
- `docs/index.md`
  - Please add a `.` at the end of the description
  - The output of the example query is missing the end line it should be added
  - Please format the query with `2 indent spaces` with [free formatted](https://www.freeformatter.com/sql-formatter.html#before-output)
  - Also please make sure that the `Configuration section` is in sync with the changes suggested for the config/semgrep.spc file.
- `semgrep/plugin.go`
  - The indentation is incorrect please use Ctrl + S or Cmd + S in case you are using a code editor like VS code
  - The list of tables should be sorted in ascending order
- `semgrep/utils.go`
  - We should add the configuration for loading the connection from the cache, which ensures throttling protection, etc. 
  -  Therefore we should also add the configuration to set it back to the cache once the connection is successfully created.
- `semgrep/*`
  - The logger error messages still include the old table names that are in plural please update them to use the updated table names for instance `plugin.Logger(ctx).Error("semgrep_deployment.listDeployments", "connection_error", err)` instead of `plugin.Logger(ctx).Error("semgrep_deployments.listDeployments", "connection_error", err)` (Extend to all tables)
  - Please update the table function names to singular for instance `tableDeployment` instead of `tableDeployments` (Extend to all tables)
- `README`
  - Please update the community link to 
  `Community: [Join #steampipe on Slack →](https://turbot.com/community/join)`
  - The output of the example query is missing the end line it should be added
  - `Configure the api token` here `API` should be in caps

**Comment by madhushreeray30** [comment]
Thanks @jplanckeel for the fixes 👍 . Can you please take a look at the following suggestions
- `config/opsgenie.spc`
  - The connection name should be `opsgenie`
  - Please make sure there is a single space between the # and the value like the url
- `docs/tables`
  - The formatting of the queries are incorrect, we can use [free formatted](https://www.freeformatter.com/sql-formatter.html#before-output) (2 indent spaces) for formatting the queries
- `docs/index.md`
  - The formatting of the query is incorrect, we can use [free formatted](https://www.freeformatter.com/sql-formatter.html#before-output) (2 indent spaces) for formatting the queries
  - The `icon_url` and `og_image` are missing 
  - Please update the configuration section with the latest details as per the opsgenie.spc file
- `opsgenie/*`
  - Please make all the table names as singular and make similar changes in any place they have been used, for instance 
    - `opsgenie_alert` instead of `opsgenie_alerts`
    - `tableOpsgenieAlert` instead of `tableOpsgenieAlerts`
- `CHANGELOG`
  - Please update with the new singular table names
- `README`
  - Please update the configuration section with the latest details as per the `opsgenie.spc` file
  - The formatting of the query is incorrect, we can use [free formatted](https://www.freeformatter.com/sql-formatter.html#before-output) (2 indent spaces) for formatting the queries
- `go.mod`
  - Please recompile the plugin with steampipe-plugin-sdk v5.6.2
- `.vscode`
  - I think we don't need this folder so we can remove it

**Comment by jplanckeel** [comment]
for me, i have fix all issues, is missing only og_image file ;)
